### ISSUE TITLE
`(encode|parse)AbiParameters` detects types correctly when passed as string but not array

### ISSUE THREAD

**Issue by wottpal** [wevm/abitype#231]
### Describe the bug

**This doesn't work:**

```ts
encodeAbiParameters(parseAbiParameters(["(uint256 a)", "(uint256 b)"]), [
	{ a: BigInt(1) },
	{ b: BigInt(1) },
])
```

Error: `Source has 2 element(s) but target allows only 1`

**This works:**

```ts
encodeAbiParameters(parseAbiParameters(["(uint256 a),(uint256 b)"]), [
	{ a: BigInt(1) },
	{ b: BigInt(1) },
])
```

Sorry, in case there has been a misconception from my side :)

Cheers, Dennis

### Package Version

1.0.0 (installed by viem@2.7.20)

### TypeScript Version

5.3.2

### Validations

- [X] Checked there isn't [already an issue](https://github.com/wevm/abitype/issues) that exists for the bug you encountered.
- [X] Followed the [Code of Conduct](https://github.com/wevm/.github/blob/main/CODE_OF_CONDUCT.md).

**Comment by tmm** [comment]
Just confirmed that this works at runtime, but not compile time. Attaching [TypeScript Playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgUwB5mQYxgFQJ4YDyAZnAL5zFQQhwDkAbsDMgM4x0BQoksicYAIZRWyAIIAjYAAVhgkMhYjylarTqCpMAsi6cEnOHEwQAduwFyFS1nAC8lkeKmyo8xchEAKANp0vAK7ApjAATACsAGxwggCUdAA09IHBYVFwEvEAurGGKOhYuDokXkJu1p6ssQB0MBAAogCOAYIANvhExAA89QXYyAAmAHxeuWSc+nkm5vBl7jb2jqKSMlYe3n4pIRHRcQlbadGZdDl5aBjYHcglcxUiNXVNLe3F3b0XLMOjnOOc2hhwd6FQaLKDIQQDMytPBwHx5AxGIxgiFQmH-ZAALnoMACYFaujySPBkNM0OMNEgpmQIVYWORJLJcMRiIRzMR9NRcHRWLoQW2US4bPZxM5pncPMEgrZZAShLgWTyMvhco5pLROh5OLxBOZqrJJnAZmpMFpcD1MKZbNZQvNXI19D5hylNpFargYoUPIkzsRSuZCqMSoVQA).

Great first issue for someone looking to dive into advanced TypeScript!

**Comment by xenoliss** [comment]
Want to give it a try! The issue seemsto be in the` Filter<Mapped, never>[0]`, which incorrectly assumes that there is only one element.

**Comment by xenoliss** [comment]
@tmm Opened a PR for review  here https://github.com/wevm/abitype/pull/232
