### ISSUE TITLE
parseAbi fails when the human readable ABI contains a `fallback()` function

### ISSUE THREAD

**Issue by joaquim-verges** [wevm/abitype#253]
### Describe the bug

Works fine with `receive()`, but `fallback()` throws an error. See steps to reproduce below.

### Steps To Reproduce

```ts
    const abi = formatAbi([
      {
        stateMutability: "payable",
        type: "fallback",
        inputs: [],
        outputs: [],
      },
    ]);
    const abi2 = parseAbi(abi);
    // throws
    // UnknownSignatureError: Unknown signature.
    // Details: fallback()
    // Version: abitype@1.0.5
```

### Package Version

1.0.5

### TypeScript Version

5.0.4

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/abitype/issues) for the bug I encountered.

**Comment by Raiden1411** [comment]
This was changed in #229 but the format function change wasn't made to accommodate to those changes. See [here](https://github.com/wevm/abitype/blob/6cb18b5ac7177aa819a8d6d471b78596b4564d22/packages/abitype/src/human-readable/formatAbiItem.ts#L129).

You can create a PR with these changes if you want.

**Comment by KedziaPawel** [comment]
hey @Raiden1411 , I've created the PR https://github.com/wevm/abitype/pull/259 that addresses the issue. If you could take a look that would be awesome
