### ISSUE TITLE
EIP712 - Cannot pass a string as `chainId`

### ISSUE THREAD

**Issue by freemanzMrojo** [wevm/abitype#256]
### Describe the bug

Currently the `TypedDataDomain` looks like this:

```
export type TypedDataDomain = {
  chainId?: number | undefined
  name?: string | undefined
  salt?: ResolvedRegister['bytesType']['outputs'] | undefined
  verifyingContract?: Address | undefined
  version?: string | undefined
}
```

Sometimes the `chainId` might be larger than a `number`, so I was wondering whether it would be possible to also support `string` and `bigint` (or maybe just `string`) for that field. [In the spec](https://eips.ethereum.org/EIPS/eip-712#definition-of-domainseparator) the attribute is expected to be an `uint256`.

I have seen in another "famous library" (:p) that the type for `chainId` is `number | bigint | string | null`.

Thanks in advance.

### Expected Behavior

I can pass a `string` as `chainId`. Specifically, I would like to be able to pass these values:

1. `14018334920824264832118464179726739019961432051877733167310318607178`
2. `1176455790972829965191905223412607679856028701100105089447013101863`
3. `20257036855429895315704288894496386224204271168750785572924599986678`

### Package Version

1.0.6

### TypeScript Version

5.6.3

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/abitype/issues) for the bug I encountered.

**Comment by tmm** [comment]
What chain IDs are these?

**Comment by freemanzMrojo** [comment]
Hi @tmm ,

Thanks for coming back to me! Those IDs are the values used by VeChain as `chainId` for the different networks in order to apply EIP712. 

Internally they are the Genesis Block ID since there is no native `chainId`. So for the values provided above:
- **Mainnet**: `14018334920824264832118464179726739019961432051877733167310318607178` in hex is `851CAF3CFDB6E899CF5958BFB1AC3413D346D43539627E6BE7EC1B4A` so the Genesis Block ID is that value => https://explore.vechain.org/blocks/0x00000000851caf3cfdb6e899cf5958bfb1ac3413d346d43539627e6be7ec1b4a
- **Testnet**: `1176455790972829965191905223412607679856028701100105089447013101863`  in hex is `B2BCE3C70BC649A02749E8687721B09ED2E15997F466536B20BB127` so the Genesis Block ID is that value => https://explore-testnet.vechain.org/blocks/0x000000000b2bce3c70bc649a02749e8687721b09ed2e15997f466536b20bb127
- **Solo** (local): In this case the value varies depending on the content of the custom genesis file, but by default it is `20257036855429895315704288894496386224204271168750785572924599986678`.

I work for VeChain. Any further input you need just let me know, thanks for your help!
